// Auto-generated by task-worker-api/tools/gen_typescript.py — DO NOT EDIT.
// Regenerate with: python tools/gen_typescript.py
// Source schemas: src/task_worker_api/schemas/*.py

// Enums ------------------------------------------------------

export type TaskType =
  | 'render'
  | 'gs_build'
  | 'gs4d_build'
  | 'segmentation'
  | 'model_initializing'
  | 'apple_ml_gs'
  | 'detect_cut_planes'
  | 'cinematic_baking'
  | 'deploy_case'
  | 'generate_synthetic'
  | 'finalize_synthetic'
  | 'finalize_segment'
  | 'spatial_recon'
;

export const TaskType = {
  RENDER: 'render' as const,
  GS_BUILD: 'gs_build' as const,
  GS4D_BUILD: 'gs4d_build' as const,
  SEGMENTATION: 'segmentation' as const,
  MODEL_INITIALIZING: 'model_initializing' as const,
  APPLE_ML_GS: 'apple_ml_gs' as const,
  DETECT_CUT_PLANES: 'detect_cut_planes' as const,
  CINEMATIC_BAKING: 'cinematic_baking' as const,
  DEPLOY_CASE: 'deploy_case' as const,
  GENERATE_SYNTHETIC: 'generate_synthetic' as const,
  FINALIZE_SYNTHETIC: 'finalize_synthetic' as const,
  FINALIZE_SEGMENTATION: 'finalize_segment' as const,
  SPATIAL_RECONSTRUCTION: 'spatial_recon' as const,
} as const;

export enum TaskStatus {
  PENDING = 0,
  CLAIMED = 1,
  IN_PROGRESS = 2,
  COMPLETED = 3,
  FAILED = 4,
  CANCELLED = 5,
}

export type TaskStatusName =
  | 'pending'
  | 'claimed'
  | 'in_progress'
  | 'completed'
  | 'failed'
  | 'cancelled'
;

// Task envelope ---------------------------------------------

/** What GET /tasks/{id} and GET /tasks return for each task row. */
export interface TaskEnvelope {
  id: number;
  task_type: TaskType;
  case_id: number | null;
  item_key: string;
  /** Numeric status code — prefer `status_name` for comparisons. */
  status: number;
  /** String form of TaskStatus, lowercase. */
  status_name: TaskStatusName;
  worker_id: string | null;
  params: Record<string, unknown>;
  result: Record<string, unknown> | null;
  error: string | null;
  progress: Record<string, unknown> | null;
  cancelled_reason: string | null;
  created_at: string | null;
  updated_at: string | null;
  claimed_at: string | null;
  completed_at: string | null;
}

// Task param schemas ---------------------------------------

/**
 * Input for the Blender worker's detect_cut_planes handler.
 */
export interface DetectCutPlanesParams {
  /** Absolute path to the input STL on the shared volume. */
  input_path: string;
  max_results?: number;
  angle_tol_deg?: number;
  planar_tol_mm?: number;
  min_area_mm2?: number;
  connected?: boolean;
  connected_count?: number;
}

/**
 * Input for the Blender worker's model_initializing handler.
 */
export interface ModelInitializingParams {
  /** Stable job identifier for metadata mirror. */
  job_id: string;
  /** Absolute STL path on the shared volume. */
  input_path: string;
  /** Filename stem for outputs. */
  base_name: string;
}

/**
 * Input for the Blender worker's cinematic_baking handler.
 */
export interface CinematicBakingParams {
  /** Stable job identifier for metadata mirror. */
  job_id: string;
  /** Absolute preview GLB path on the shared volume. */
  input_path: string;
  /** Filename stem for outputs; _finalized.glb appended. */
  base_name: string;
  /** Optional worker material registry id. Omit for the deployment's Current/default material. */
  material_id?: string;
  /** Optional Bioform Pattern Scale override; requires material_id and must be supported by that material. */
  pattern_scale?: number;
}

/**
 * Input for the colmap-splat worker's gs_build handler.
 */
export interface GsBuildParams {
  /** Scene directory on shared volume. */
  scene?: string;
  /** Alias for `scene`. */
  scene_path?: string;
  /** Scene id; defaults to dir basename. */
  scene_id?: string;
  /** Prior-phase PLY to warm-start from (4D); absolute, on shared volume. */
  warm_start_ply?: string;
  method?: string;
  iterations?: number;
  max_image_size?: number;
  max_splats?: number;
  sh_degree?: number;
  seed?: number;
  sift_max_image_size?: number;
  num_threads?: number;
  background?: string;
  strategy?: string;
  /** Run COLMAP dense MVS for splat init (adds 5–30 min). */
  dense_init?: boolean;
}

/**
 * Input for Neural-Canvas's one-shot segmentation handler.
 */
export interface SegmentationParams {
  /** NIfTI volume on the shared volume. */
  input_path: string;
  /** vista3d | medsam3 | medsam2 | openmap_* | totalsegmentator_* */
  model: string;
  /** Durable shared dir the worker writes the mask into (server-minted). */
  output_dir: string;
  result_mask_id?: string;
  result_mask_name?: string;
  result_mask_color?: string;
  case_id?: number;
  dicom_id?: number;
  /** Applied user mask id. */
  mask_id?: string;
  /** 'primary' | 'native'. */
  result_frame?: string;
  min_volume_cm3?: number;
  boundary_smoothing?: boolean;
  boundary_smoothing_strength?: string;
  bbox?: Array<number>;
  prompt?: string;
  axis?: number;
  threshold?: number;
  nms_iou?: number;
  window_center?: number;
  window_width?: number;
  volume_threshold?: number;
  merge_regions?: boolean;
  fill_empty_slices?: boolean;
  max_fill_gap?: number;
  target?: string;
  modality?: string;
  label_prompt?: Array<number>;
  intensity_refine?: boolean;
  grow_max_distance?: number;
  grow_shrink_voxels?: number;
  grow_gradient_threshold?: number;
  grow_intensity_sigma?: number;
  grow_debug?: boolean;
  smooth_edge?: boolean;
  smooth_seeds?: boolean;
  output_ext?: string;
  fast?: boolean;
  seed_slice?: number;
  seed_box?: Array<number>;
  medsam2_modality?: string;
  labels?: Array<string>;
}

/**
 * Input for the assetbundle-builder worker's deploy_case handler.
 */
export interface DeployCaseParams {
  content_path: string;
  build_target?: string;
}

/**
 * Input for the synthetic-generator SRR compute.
 */
export interface GenerateSyntheticParams {
  sources: Array<SyntheticSource>;
  source_dicom_ids: Array<number>;
  reference_dicom_id: number;
  /** Reference NIfTI GetSize() [X,Y,Z]. */
  reference_size: Array<number>;
  /** {'mode':'full'} or {'mode':'roi','bounds':{...}}. */
  synthetic_roi: Record<string, unknown>;
  /** Server-minted staging dir on the shared volume. */
  staging_dir: string;
  /** Server-minted final dicom dir on the shared volume. */
  output_dir: string;
  output_filename: string;
  name: string;
  author_id: number;
  /** NiftyMIC tunables; image defaults apply when empty. */
  niftymic?: Record<string, unknown>;
}

/**
 * Locate one immutable capture under the worker's shared-data root.
 */
export interface SpatialReconstructionParams {
  case_guid: string;
  capture_hash: string;
  capture_root_rel: string;
  coordinate_frame: string;
}


/** Map of TaskType → params schema for typed dispatch. */
export interface TaskParamsByType {
  'detect_cut_planes': DetectCutPlanesParams;
  'model_initializing': ModelInitializingParams;
  'cinematic_baking': CinematicBakingParams;
  'gs_build': GsBuildParams;
  'gs4d_build': GsBuildParams;
  'segmentation': SegmentationParams;
  'deploy_case': DeployCaseParams;
  'generate_synthetic': GenerateSyntheticParams;
  'spatial_recon': SpatialReconstructionParams;
}
