// Auto-generated by task-worker-api/tools/gen_typescript.py — DO NOT EDIT.
// Regenerate with: python tools/gen_typescript.py
// Source schemas: src/task_worker_api/schemas/*.py

// Enums ------------------------------------------------------

export type TaskType =
  | 'render'
  | 'gs_build'
  | 'segmentation'
  | 'model_initializing'
  | 'apple_ml_gs'
  | 'detect_cut_planes'
;

export const TaskType = {
  RENDER: 'render' as const,
  GS_BUILD: 'gs_build' as const,
  SEGMENTATION: 'segmentation' as const,
  MODEL_INITIALIZING: 'model_initializing' as const,
  APPLE_ML_GS: 'apple_ml_gs' as const,
  DETECT_CUT_PLANES: 'detect_cut_planes' as const,
} as const;

export enum TaskStatus {
  PENDING = 0,
  CLAIMED = 1,
  IN_PROGRESS = 2,
  COMPLETED = 3,
  FAILED = 4,
  CANCELLED = 5,
}

export type TaskStatusName =
  | 'pending'
  | 'claimed'
  | 'in_progress'
  | 'completed'
  | 'failed'
  | 'cancelled'
;

// Task envelope ---------------------------------------------

/** What GET /tasks/{id} and GET /tasks return for each task row. */
export interface TaskEnvelope {
  id: number;
  task_type: TaskType;
  case_id: number | null;
  item_key: string;
  /** Numeric status code — prefer `status_name` for comparisons. */
  status: number;
  /** String form of TaskStatus, lowercase. */
  status_name: TaskStatusName;
  worker_id: string | null;
  params: Record<string, unknown>;
  result: Record<string, unknown> | null;
  error: string | null;
  progress: Record<string, unknown> | null;
  cancelled_reason: string | null;
  created_at: string | null;
  updated_at: string | null;
  claimed_at: string | null;
  completed_at: string | null;
}

// Task param schemas ---------------------------------------

/**
 * Input for the Blender worker's detect_cut_planes handler.
 */
export interface DetectCutPlanesParams {
  /** Absolute path to the input STL on the shared volume. */
  input_path: string;
  max_results?: number;
  angle_tol_deg?: number;
  planar_tol_mm?: number;
  min_area_mm2?: number;
  connected?: boolean;
  connected_count?: number;
}

/**
 * Input for the Blender worker's model_initializing handler.
 */
export interface ModelInitializingParams {
  /** Stable job identifier for metadata mirror. */
  job_id: string;
  /** Absolute STL path on the shared volume. */
  input_path: string;
  /** Filename stem for outputs. */
  base_name: string;
}

/**
 * Input for the colmap-splat worker's gs_build handler.
 */
export interface GsBuildParams {
  /** Scene directory on shared volume. */
  scene?: string;
  /** Alias for `scene`. */
  scene_path?: string;
  /** Scene id; defaults to dir basename. */
  scene_id?: string;
  method?: string;
  iterations?: number;
  max_image_size?: number;
  max_splats?: number;
  sh_degree?: number;
  seed?: number;
  sift_max_image_size?: number;
  num_threads?: number;
  background?: string;
  strategy?: string;
}

/**
 * Input for Neural-Canvas's segmentation handler.
 */
export interface SegmentationParams {
  /** NIfTI volume on the shared volume. */
  input_path: string;
  /** Segmentation model: 'vista3d' or 'medsam3'. */
  model: string;
  /** Target label names. */
  labels?: Array<string>;
  case_id?: number;
  dicom_id?: number;
  /** Mask identifier for result mirror. */
  mask_id?: string;
}


/** Map of TaskType → params schema for typed dispatch. */
export interface TaskParamsByType {
  'detect_cut_planes': DetectCutPlanesParams;
  'model_initializing': ModelInitializingParams;
  'gs_build': GsBuildParams;
  'segmentation': SegmentationParams;
}
