"""Generate TypeScript type definitions from the Pydantic schemas.

Writes to ``artifacts/task-worker-types/index.ts``. Runs as a CI job
that regenerates and diffs — drift between Python and TS fails the job.

Why hand-rolled vs using pydantic-to-typescript / datamodel-code-generator:
the schemas here are small and deliberately simple (flat field sets, no
nested models beyond a couple of enums). A ~150-line script covers every
shape we use and adds zero third-party dependencies to the package's
build. When the schema set grows past ~20 types or starts using unions
and discriminators, swap in a real codegen library.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from task_worker_api.enums import TaskStatus, TaskType
from task_worker_api.schemas import TASK_PARAMS_SCHEMAS


_HEADER = """// Auto-generated by task-worker-api/tools/gen_typescript.py — DO NOT EDIT.
// Regenerate with: python tools/gen_typescript.py
// Source schemas: src/task_worker_api/schemas/*.py

"""


def _pyty_to_ts(schema: dict, defs: dict[str, dict]) -> str:
    """Map a Pydantic JSON-schema node to a TS type expression."""
    # $ref → reference to a named type
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]

    # enum → TS string-literal union
    if "enum" in schema:
        return " | ".join(f"'{v}'" for v in schema["enum"])

    # anyOf / oneOf → TS union; drop null for optionality (we emit `?`)
    if "anyOf" in schema or "oneOf" in schema:
        variants = schema.get("anyOf") or schema.get("oneOf")
        non_null = [v for v in variants if v.get("type") != "null"]
        if len(non_null) == 1:
            return _pyty_to_ts(non_null[0], defs)
        return " | ".join(_pyty_to_ts(v, defs) for v in non_null)

    t = schema.get("type")
    if t == "integer" or t == "number":
        return "number"
    if t == "string":
        return "string"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        items = schema.get("items") or {}
        return f"Array<{_pyty_to_ts(items, defs)}>"
    if t == "object":
        ap = schema.get("additionalProperties")
        if isinstance(ap, dict):
            return f"Record<string, {_pyty_to_ts(ap, defs)}>"
        if schema.get("properties"):
            return _render_inline_object(schema, defs)
        return "Record<string, unknown>"

    return "unknown"


def _render_inline_object(schema: dict, defs: dict[str, dict]) -> str:
    required = set(schema.get("required") or [])
    props = schema.get("properties") or {}
    fields = []
    for name, field_schema in props.items():
        opt = "" if name in required else "?"
        ts_type = _pyty_to_ts(field_schema, defs)
        desc = field_schema.get("description")
        if desc:
            fields.append(f"  /** {desc} */")
        fields.append(f"  {name}{opt}: {ts_type};")
    return "{\n" + "\n".join(fields) + "\n}"


def _render_interface(name: str, schema: dict, defs: dict[str, dict]) -> str:
    body = _render_inline_object(schema, defs)
    title_line = schema.get("description")
    comment = f"/**\n * {title_line}\n */\n" if title_line else ""
    return f"{comment}export interface {name} {body.replace('{', '{', 1)}\n"


def _emit_enums() -> str:
    lines = [
        "// Enums ------------------------------------------------------",
        "",
        "export type TaskType =",
        *[f"  | '{t.value}'" for t in TaskType],
        ";",
        "",
        "export const TaskType = {",
        *[f"  {t.name}: '{t.value}' as const," for t in TaskType],
        "} as const;",
        "",
        "export enum TaskStatus {",
        *[f"  {s.name} = {int(s)}," for s in TaskStatus],
        "}",
        "",
        "export type TaskStatusName =",
        *[f"  | '{s.name.lower()}'" for s in TaskStatus],
        ";",
        "",
    ]
    return "\n".join(lines) + "\n"


def _emit_claimed_task() -> str:
    """The typed wrapper workers receive. Mirrors ClaimedTask.from_dict's
    expected envelope — what the backend's `_task_to_dict` emits."""
    return """// Task envelope ---------------------------------------------

/** What GET /tasks/{id} and GET /tasks return for each task row. */
export interface TaskEnvelope {
  id: number;
  task_type: TaskType;
  case_id: number | null;
  item_key: string;
  /** Numeric status code — prefer `status_name` for comparisons. */
  status: number;
  /** String form of TaskStatus, lowercase. */
  status_name: TaskStatusName;
  worker_id: string | null;
  params: Record<string, unknown>;
  result: Record<string, unknown> | null;
  error: string | null;
  progress: Record<string, unknown> | null;
  cancelled_reason: string | null;
  created_at: string | null;
  updated_at: string | null;
  claimed_at: string | null;
  completed_at: string | null;
}

"""


def _emit_schemas() -> str:
    parts = ["// Task param schemas ---------------------------------------", ""]
    for tt, model_cls in TASK_PARAMS_SCHEMAS.items():
        interface_name = model_cls.__name__
        schema = model_cls.model_json_schema()
        defs = schema.get("$defs") or {}
        parts.append(_render_interface(interface_name, schema, defs))

    # Emit a discriminated union helper so TS callers can narrow on task_type.
    lines = ["", "/** Map of TaskType → params schema for typed dispatch. */", "export interface TaskParamsByType {"]
    for tt, model_cls in TASK_PARAMS_SCHEMAS.items():
        lines.append(f"  '{tt.value}': {model_cls.__name__};")
    lines.append("}")
    parts.append("\n".join(lines) + "\n")
    return "\n".join(parts)


def generate() -> str:
    return _HEADER + _emit_enums() + _emit_claimed_task() + _emit_schemas()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate TS types from Pydantic schemas.")
    parser.add_argument(
        "--out", type=Path,
        default=Path(__file__).resolve().parent.parent / "artifacts" / "task-worker-types" / "index.ts",
        help="Output .ts file. Parent dirs created automatically.",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if the file on disk differs from the regenerated output.",
    )
    args = parser.parse_args()

    generated = generate()
    args.out.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not args.out.is_file():
            print(f"ERROR: {args.out} does not exist. Run without --check to create it.")
            return 1
        current = args.out.read_text(encoding="utf-8")
        if current != generated:
            print("ERROR: generated TS differs from committed artifact.")
            print(f"  Regenerate with: python {Path(__file__).name}")
            return 1
        print(f"OK: {args.out} matches generated output.")
        return 0

    args.out.write_text(generated, encoding="utf-8")
    print(f"Wrote {args.out} ({len(generated.splitlines())} lines).")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
